# dynmap-residence configuration
#
update:
  # Seconds between checks for Residence updates
  period: 300
  # Listen for update events from Residence, and do immediate updates (if true)
  onchange: true

layer:
  name: "Residence"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 1

# Set true to show 3D volumes for zones  
use3dregions: false

# How deep to nest residence subzones
resdepth: 2

# Format for popup - substitute values for macros
infowindow: '<div class="infowindow"><span style="font-size:120%;">%regionname%</span><br /> Owner <span style="font-weight:bold;">%playerowners%</span><br />Flags<br /><span style="font-weight:bold;">%flags%</span></div>'

regionstyle:
  strokeColor: "#FF0000"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#FF0000"
  fillOpacity: 0.35
  
# Optional setting to limit which regions to show, by name - if commented out, all regions are shown
visibleregions: [ ]
  
# Optional setting to hide specific regions, by name
hiddenregions: [ ]
  
# Optional per-region overrides for regionstyle (any defined replace those in regionstyle)
custstyle:
  customizedregion:
    strokeColor: "#00FF00"
  anotherregion.subzone:
    strokeColor: "#007F00"
  

